version: '3.8'

services:
  dotnetApi:
    image: awsapi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:8080"
    volumes:
      - app-data:/app/data

  postgresdb:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 123456
    volumes:
      - ./data:/var/lib/postgresql/data  # 確保數據持久化的路徑正確
    ports:
      - "5432:5432"

volumes:
  app-data:
    driver: local
